default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  user: postgres
  port: 5432
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: product_register_development

test:
  <<: *default
  database: product_register_test

# for heroku deployment 以下の環境変数を追加
production:
  <<: *default
  database: <%= ENV['APP_DB'] %>
  username: <%= ENV['APP_DB_USERNAME'] %>
  password: <%= ENV['APP_DB_PASSWORD'] %>
  host: <%= ENV['APP_DB_HOST'] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>  #for devise / credentials.yml.enc で確認できる
